module.exports = {
    MUTED: 'MUTED',
    MUTE_ERROR: 'MUTE_ERROR',
    VOLUME_CHANGED: 'VOLUME_CHANGED',
    UPDATE_VOLUME: 'UPDATE_VOLUME',
    START_LOADING: 'START_LOADING',
    END_LOADING: 'END_LOADING',
    PLAY_ALBUM: 'PLAY_ALBUM',
    UPDATE_STATUS: 'UPDATE_STATUS',
    GET_ALBUMS: 'GET_ALBUMS',
    GET_ALBUMS_SUCCESS: 'GET_ALBUMS_SUCCESS',
    GET_ALBUMS_FAILURE: 'GET_ALBUMS_FAILURE',
    PLAY: 'PLAY',
    PAUSE: 'PAUSE'
};