module.exports = {
    PLAY_ALBUM: 'PLAY_ALBUM',
    UPDATE_STATUS: 'UPDATE_STATUS',
    GET_ALBUMS: 'GET_ALBUMS',
    GET_ALBUMS_SUCCESS: 'GET_ALBUMS_SUCCESS',
    GET_ALBUMS_FAILURE: 'GET_ALBUMS_FAILURE',
    PLAY: 'PLAY',
    PAUSE: 'PAUSE'
};